import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Adoniyas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className=' text-white bg-gradient-to-b from-gray-900 via-gray-800 to-gray-900'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
